halls/api/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path, include
from halls import views
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    HallListAPIView,
    LikeToggleAPIView
)

urlpatterns = [
    path('', HallListAPIView.as_view(), name='list'),
    path('<int:pk>/save', LikeToggleAPIView.as_view(), name='togglesave'),
]

hofvidz/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path, include
from halls import views
from tags import views as tag_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('dashboard/',views.dashboard,name='dashboard'),
    #AUTH
    path('signup',views.SignUp.as_view(), name='signup'),
    path('login',auth_views.LoginView.as_view(),name='login'),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
    #hall - crud
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.ViewHall.as_view(), name='view_hall'),
    path('halloffame/<int:pk>/update', views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete', views.DeleteHall.as_view(), name='delete_hall'),
    path('halloffame/<int:pk>/save', views.SavehallView.as_view(), name='save_hall'),
    path('user/<int:pk>/',views.userdetail,name='user_dash'),

    #Video
    path('halloffame/<int:pk>/addvideo', views.VideoAddView.as_view(), name='addvideo'),
    path('halloffame/<int:pk>/deletevideo', views.DeleteVideo.as_view(), name='deletevideo'),
    path('video/search', views.video_search, name='video_search'),
    path('hall/search', views.hall_search, name='hall_search'),

    path('api/halls/',include(('halls.api.urls','halls'), namespace='halls-api')),
    path('api/tags/',include(('tags.api.urls','tags'), namespace='tags-api')),
    path('tags/<tag>',tag_view.TagsView.as_view(), name='tags-view'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django_mysql.models import ListCharField
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from tags.signal import parsed_tags
from django.conf import settings


# Create your models here.

class HallManager(models.Manager):
    def savehall(self,user,parent_obj):
        qs = self.get_queryset().filter(user=user,parent=parent_obj)
        if qs.exists():
            return None
        obj = self.model(
            parent = parent_obj,
            user = user,
            title = parent_obj.title,
            tags = parent_obj.tags
        )
        obj.save()

        return obj
    
    def save_toggle(self, user, hall_obj):
        if user in hall_obj.saved.all():
            print("saved")
            is_liked = True
            hall_obj.saved.remove(user)
        else:
            is_liked = False
            print("unsaved")
            hall_obj.saved.add(user)
        return is_liked


class Hall(models.Model):
    parent = models.ForeignKey("self",blank=True,null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_halls')
    saved = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='saved')
    # tags = ListCharField(
    #     base_field=models.CharField(max_length=20),
    #     blank=True,
    #     size=5,
    #     max_length=(5 * 21)  # 6 * 10 character nominals, plus commas
    # )
    tags = models.CharField(max_length=255, blank=True)

    objects = HallManager()
    def __str__(self):
        return self.title

# def hall_save_receiver2(sender, instance, *args, **kwargs):
#         instance.tags = instance.tags.split(",")

# pre_save.connect(hall_save_receiver2, sender = Hall)  

def hall_save_receiver(sender, instance, created, *args, **kwargs):
    # if created:
    parsed_tags.send(sender=instance.__class__,tags_list=instance.tags.split(","))

post_save.connect(hall_save_receiver, sender = Hall)  




    

class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall,related_name='videos',on_delete=models.CASCADE)

halls/forms.py
from .models import Video, Hall
from django import forms
from django.db import models
from django_mysql.forms import SimpleListField
from django.forms import modelformset_factory

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields=['url','title']
        labels={'url':'YouTube URL'}
        widgets = {'Id': forms.HiddenInput()}

VideoFormSet = modelformset_factory(
    Video, form = VideoForm, extra=1
)

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for Videos:')

class CreateForm(forms.ModelForm):
    # title = forms.CharField()
    # tags = SimpleListField(models.CharField(max_length=20),widget=forms.TextInput(attrs={'data-role': 'tagsinput','id':'taginput'}))
    class Meta:
        model = Hall
        fields=['title','tags']
        widgets = {
            'tags': forms.TextInput(attrs={'data-role': 'tagsinput','id':'taginput'}),
        }

halls/api/views.py
from rest_framework import generics
from django.db.models import Q

from halls.models import Hall
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework.response import Response
from .serializers import HallModelSerializer
from .pagination import StandardResultsPagination

class HallListAPIView(generics.ListAPIView):
    serializer_class = HallModelSerializer
    pagination_class = StandardResultsPagination

    def get_serializer_context(self, *args, **kwargs):
        context = super(HallListAPIView, self).get_serializer_context(*args, **kwargs)
        context['request'] = self.request
        return context

    def get_queryset(self):
        results = Hall.objects.all()
        results = results.filter(parent__isnull=True)
        query = self.request.GET.get("q",None)
        print(query)
        if not query==None:
            results = results.filter(title__icontains=query)
        tag = self.request.GET.get("tag",None)
        print(tag)                
        if not tag==None:
            results = results.filter(tags__icontains=tag)
        print(results)
        if self.request.user.is_authenticated:
            results = results.exclude(user=self.request.user)

        return results
        

class LikeToggleAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    def get(self, request, pk, format=None):
        hall_qs = Hall.objects.filter(pk=pk)
        message = "Not allowed"
        if request.user.is_authenticated:
            is_saved = Hall.objects.save_toggle(request.user,hall_qs.first())
            return Response({'saved':is_saved})
        
        return Response({"message":message},status=400)

halls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import Hall
from .models import Video
from .forms import VideoForm, SearchForm, CreateForm, VideoFormSet
from django.http import Http404, JsonResponse, HttpResponseRedirect
from django.forms.utils import ErrorList
import urllib
import requests
from rest_framework import serializers
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from tags.models import Tags
from django.conf import settings
from django.contrib.auth.models import User

YOUTUBE_API_KEY = 'AIzaSyAODfuLUC8u5j6cFp3Wxj4_rBiPA-XJxcI'

# Create your views here.
def home(request):
    search_form = SearchForm()
    recent_halls = Hall.objects.all().order_by('-id')
    tags = Tags.objects.all().order_by('-tagTimes')[0:5]
    if request.user.is_authenticated:
        recent_halls = recent_halls.exclude(user=request.user)
    return render(request, 'halls/home.html',{"recent_halls":recent_halls,'search_form':search_form,'tags':tags})


@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user,parent__isnull=True)
    for hall in halls:
        if hall.tags:
            hall.tags = hall.tags.split(",")
    halls_saved = request.user.saved.all()
    for item in halls_saved:
        item.tags = item.tags.split()
        print(item.tags)

    return render(request, 'halls/dashboard.html',{'halls':halls,'halls_saved':halls_saved})

def userdetail(request,pk):
    targetUser = User.objects.get(pk=pk)
    halls = Hall.objects.filter(user=targetUser)
    for hall in halls:
        if hall.tags:
            hall.tags = hall.tags.split(",")
    halls_saved = Hall.objects.filter(user=request.user,parent__isnull=False)
    return render(request, 'halls/user_detail.html',{'halls':halls,'halls_saved':halls_saved,'targetuser':targetUser})

class VideoAddView(generic.TemplateView):
    template_name = "halls/add_video.html"
    search_form = SearchForm()

    def get(self, *args, **kwargs):
        formset = VideoFormSet(queryset=Video.objects.none())
        search_form = SearchForm()
        return self.render_to_response({'video_formset': formset,'search_form':search_form})

    # Define method to handle POST request
    def post(self,request,pk, *args, **kwargs):

        formset = VideoFormSet(data=self.request.POST)
        
        for form in formset:
            print("----------------------------")
            print(form)
            if formset.is_valid():
                video = Video()
                video.url = form.cleaned_data['url']
                parsed_url = urllib.parse.urlparse(video.url)
                video_id = urllib.parse.parse_qs(parsed_url.query).get("v")
                if video_id:
                    video.youtube_id = video_id[0]
                    response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')
                    json = response.json()
                    
                    video.title = json['items'][0]['snippet']['title']           
                    video.hall = Hall.objects.get(pk=pk)
                    video.save()
        
                else:
                    errors = form._errors.setdefault('url',ErrorList())
                    errors.append('Needs to be a Youtube url.')
        
        return redirect('view_hall',pk)

        # Check if submitted forms are valid
        # if formset.is_valid():
        #     formset.save()
        #     return redirect(reverse_lazy("dashboard"))

        return self.render_to_response({'video_formset': formset})

@login_required
def add_video(request,pk):
    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    print(request)
    if request.method == 'GET':
        return render(request, 'halls/add_video.html',{'hall':hall,'form':form,'search_form':search_form})

    if not hall.user == request.user:
        raise Http404

    if request.method == 'POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get("v")
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')
                json = response.json()
                
                video.title = json['items'][0]['snippet']['title']           
                video.hall = Hall.objects.get(pk=pk)
                video.save()
                return redirect('view_hall',pk)
            else:
                errors = form._errors.setdefault('url',ErrorList())
                errors.append('Needs to be a Youtube url.')
                
            

    return render(request, 'halls/add_video.html',{"form":form,"search_form":search_form})

@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    print(search_form)
    print(request.GET)
    temp=request.GET
    if "quote" in request.GET:
        print (request.GET.__getitem__("quote"))

    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={encoded_search_term}&key={ YOUTUBE_API_KEY }')
        if "quote" in request.GET:
            nextPage = request.GET.__getitem__("quote")
            response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&pageToken={nextPage}&maxResults=6&q={encoded_search_term}&key={ YOUTUBE_API_KEY }')
        return JsonResponse(response.json());
    return JsonResponse({'error':'not able to find the videos'})  

def hall_search(request):
    data=[]
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        halls = Hall.objects.filter(title__icontains=encoded_search_term)
        # response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={encoded_search_term}&key={ YOUTUBE_API_KEY }')
        data = serializers.serialize('json',halls,fields=('title','id'))
        print(data)
        return JsonResponse(data,safe=False);
    return JsonResponse({'error':'not able to find the videos'})  


class SignUp(generic.CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy('home')
    template_name='registration/signup.html'

    #override form_valid to login the user??
    def form_valid(self, form):
        view = super(SignUp,self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username,password=password)
        login(self.request,user)
        return view


class SavehallView(generic.View):
    def get(self,request,pk,*args,**kwargs):
        hall = get_object_or_404(Hall,pk=pk)
        if request.user.is_authenticated:
            new_hall = Hall.objects.savehall(request.user,hall)
            return HttpResponseRedirect("/")
        return redirect("view_hall",hall.id)

class CreateHall(LoginRequiredMixin,generic.CreateView):
    # model = Hall
    # fields = ['title','tags']
    form_class = CreateForm
    template_name = 'halls/create_hall.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        #add 
        form.instance.user = self.request.user
        super(CreateHall,self).form_valid(form)
        new_id = Hall.objects.latest('id')
        print(new_id.id)
        return redirect("view_hall",new_id.id)


class ViewHall(generic.DetailView):
    model = Hall
    template_name = 'halls/detail.html'

class UserDetailview(generic.DetailView):
    model = User
    template_name='halls/user_detail.html'

class UpdateHall(LoginRequiredMixin, generic.UpdateView):
    # model = Hall
    # fields=['title','tags']
    queryset = Hall.objects.all()
    form_class = CreateForm
    template_name = 'halls/update_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateHall,self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall
    
    def form_valid(self,form):
        super(UpdateHall,self).form_valid(form)
        hall = super(UpdateHall,self).get_object()
        hall.save()
        return redirect("view_hall",hall.id)


class DeleteHall(LoginRequiredMixin, generic.DeleteView):
    model = Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall,self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall

class DeleteVideo(LoginRequiredMixin,generic.DeleteView):
    model = Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo,self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video
    
    def delete(self,request,pk):
        video = super(DeleteVideo,self).get_object()
        hall_id = video.hall.id
        video.delete()
        return redirect("view_hall",hall_id)

halls/templates/halls/add_video.html
{% extends 'halls/base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <h1>Add Video {{hall.title}} </h1>
    <!-- <form method="post" id="video_url">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}

        <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
        
        {{field.errors}}
        {{field.label_tag}}
        {% render_field field class="form-control" %}
        </div>
        {% endfor %}
        {% for field in form%}

        <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
        
        {{field.errors}}
        {{field.label_tag}}
        {% render_field field class="form-control" %}
        </div>
        {% endfor %}
        {% for field in form %}

        <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
        
        {{field.errors}}
        {{field.label_tag}}
        {% render_field field class="form-control" %}
        </div>
        {% endfor %}
            
        <button type="submit" value="Add">Add</button>
    </form> -->
    <form id="form-container" method="POST">
        {% csrf_token %}
        {{video_formset.management_form}}
        
        {% for form in video_formset %}
        <div class="video-form">
            {% load widget_tweaks %}
            {% for field in form.visible_fields %}

            <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
            
            {{field.errors}}
            {{field.label_tag}}
            {% render_field field class="form-control" %}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <button id="add-form" type="button">Add Another Video</button>
        <button type="submit">Submit</button>
    </form>
   
        
    <form>
        {% for field in search_form %}

        <p>
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
        </p>
        
        {% endfor %}
    </form>
    <div id="search_results">
      

    </div>
    <a href="#" class="btn btn-primary" id="loadmore">Load More Videos</a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.20/angular.min.js"></script>

    <script src="{% static 'tagsinput.js' %}"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/rainbow.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/generic.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/html.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/javascript.js"></script>
    {% block script %}
    <script>
    var delayTimer;
    var nextPage;
    var addedVideo = 0;
    var videoForm = $(".video-form")
    console.log(videoForm.length)
    var formNum = $(".video-form").length
        let container = $("#form-container")
        
        let totalForms = $("#id_form-TOTAL_FORMS")
        function addVideo(video){
            console.log(video)
            if (addedVideo==0){
                $('#id_form-'+formNum+'-url').val('https://www.youtube.com/watch?v='+video.split(",")[0]);
                $('#id_form-'+formNum+'-title').val(video.split(",")[1]);
                addedVideo++
            }
            else{
                newForm = $($(".video-form").get(0)).clone()
                addedVideo++
               
               
               let formRegex = RegExp(`form-(\\d){1}-`,'g')
               console.log(formNum)

               formNum++
               console.log(formNum)
               var txt = newForm.html()
               console.log(txt)
               newForm.html(txt.replace(formRegex, `form-${formNum}-`))
       
               console.log($('#id_'+`form-${formNum}-`+'url'))
               
               newForm.insertBefore("#add-form")
               $('#id_form-'+formNum+'-url').val('https://www.youtube.com/watch?v='+video.split(",")[0]);
               $('#id_form-'+formNum+'-title').val(video.split(",")[1]);
               $("#id_form-TOTAL_FORMS").attr('value', `${formNum+1}`)
            }
            
           
       // $('#id_url').val('https://www.youtube.com/watch?v='+video_id);
       // $('#video_url').submit();

   }
$(document).ready(function(){
    // addButton.click(function(e){
    //         e.preventDefault()
    //         newForm = videoForm.clone()
    //         console.log(videoForm)
    //         var txt = newForm.html();
    //         let formRegex = RegExp(`form-(\\d){1}-`,'g')

    //         formNum++
    //         newForm.html(txt.replace(formRegex, `form-${formNum}-`))
    //         newForm.insertBefore(addButton)
            
    //         totalForms.attr('value', `${formNum+1}`)
    // })

    $('#loadmore').css("display","none");
            $('#id_search_term').keyup(function() {
                clearTimeout(delayTimer);
                $('#search_results').text('Loading...');
                delayTimer = setTimeout(function() {
                    var text = $('#id_search_term').val();
                    $.ajax({
                        url:'/video/search',
                        data:{
                            'search_term':text
                        },
                        dataType:'json',
                        success:function(data){
                            var results=" ";
                            $('#search_results').text('');
                            results+='<div class="row">';
                            data['items'].forEach(function(item){
                                results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                                results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/'+item["id"]["videoId"]+' "frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                                results += '<div class="card-body"><p class="card-text">'+ item['snippet']['title'] + '</p>';
                                results += '<a href="#" class="btn btn-primary addvideo" onclick = "addVideo(\''+item["id"]["videoId"]+','+item['snippet']['title']+'\')"> Add</a></div></div></div>';
                                // results+=item['snippet']['title'
                            });
                            results+='</div>';
                            console.log(data);
                            $('#search_results').append(results);
                            $('#loadmore').css("display","block");
                            if (data.nextPageToken){
                                nextPage = data.nextPageToken
                            }
                            let addvideoBtn = $(".addvideo")
                           },
                        error: function(data){
                            console.log("error")
                            console.log(data)
                        }
                    });
                    

                },1000);

               
            })
            

            
            $("#loadmore").click(function(event){
                event.preventDefault()
                    var text = $('#id_search_term').val();
                    $.ajax({
                        url:'/video/search',
                        data:{
                            'search_term':text,
                            'quote':nextPage
                        },
                        dataType:'json',
                        success: function(data){
                            var results=" ";
                            results+='<div class="row">';
                            data['items'].forEach(function(item){

                                results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                                results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/'+item["id"]["videoId"]+' "frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                                results += '<div class="card-body"><p class="card-text">'+ item['snippet']['title'] + '</p>';
                                results += '<a href="#" class="btn btn-primary" onclick = "addVideo(\''+item["id"]["videoId"]+','+item['snippet']['title']+'\')"> Add</a></div></div></div>';
                                // results+=item['snippet']['title'
                            });
                            results+='</div>';
                            console.log(data);
                            $('#search_results').append(results);
                            if (data.nextPageToken){
                                nextPage = data.nextPageToken
                            }else{
                                 $('#loadmore').css("display","none");
                            }
                        },
                        error: function(data){
                            console.log("error")
                            console.log(data)
                        }

            })
            })
        })
    
                console.log(formNum)
               
        
                     
</script>
{% endblock script %}
    {% endblock content %}

    

halls/templates/halls/create_hall.html
{% extends 'halls/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Create</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <input id ="taginput" type="text" value="Amsterdam,Washington,Sydney,Beijing,Cairo" data-role="tagsinput" style="color:black" > -->
        <input type="submit" value="Create Hall"></input>

    </form>
</div>
{% endblock %}


{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.20/angular.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous">
</script> -->
<script src="{% static 'tagsinput.js' %}"></script>
<!-- <script src="{% static 'app.js' %}"></script>
<script src="{% static 'app_bs3.js' %}"></script> -->
<!-- <script src="{% static 'bootstrap-tagsinput-angular.min.js' %}"></script>
<script src="{% static 'bootstrap-tagsinput.min.js' %}"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/rainbow.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/generic.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/html.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/javascript.js"></script>

{% endblock script %}

halls/templates/halls/delete_hall.html
{% extends 'halls/base.html' %}

{% block content %}

<div class="container">
    <h1>Delete Hall {{object.title}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Update Hall">Delete hall</button>

    </form>
</div>
{% endblock %}

halls/templates/halls/delete_video.html
{% extends 'halls/base.html' %}

{% block content %}

<div class="container">
    <h1>Delete Video {{object.title}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Update Hall">Delete Video</button>

    </form>
</div>
{% endblock %}